/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Enumeration;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.*;

/**
 *
 * @author yuujadz
 */
public class AddNewEmployee extends javax.swing.JPanel {

    /**
     * Creates new form AddNewEmployee
     */
    EmployeeDirectory employeeDirectory;
    
    public AddNewEmployee(EmployeeDirectory employeeDirectory) {
        this.employeeDirectory=employeeDirectory;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JFormattedTextField();
        txtAge = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtSupervisor = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnCreate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Add New Employee");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 100, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Photo:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Department:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Employee ID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Age:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Gender:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Start Date:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Level:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Supervisor:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Title:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Mobile:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 100, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Name:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });
        txtEmployeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmployeeIDKeyPressed(evt);
            }
        });
        add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, 30));
        add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 190, 30));
        add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 190, 30));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 190, 30));
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 190, 30));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 190, 30));
        add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 190, 30));
        add(txtSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 190, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("N");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("M");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("F");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 50, -1));

        btnCreate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 100, 50));

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 160, 190));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, 30));
        add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        if(txtEmployeeID.getText().equals("")||txtAge.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill in all the blanks.");        
        }else{
        
        String name = txtName.getText();
        String department = txtDepartment.getText();
        long id = Long.parseLong(txtEmployeeID.getText());
        int age = Integer.parseInt(txtAge.getText());
        String gender = getButtonGroupText(buttonGroup1);                
        String startDate = txtStartDate.getText();
        String level = txtLevel.getText();
        String title = txtTitle.getText();
        String supervisor = txtSupervisor.getText();
        String mobile = txtMobile.getText();
        String email = txtEmail.getText();
        ImageIcon photo = (ImageIcon)lblImage.getIcon();
        
        if(name.equals("")||department.equals("")||startDate.equals("")||level.equals("")||
            title.equals("")||supervisor.equals("")||mobile.equals("")||email.equals("")){
            
            JOptionPane.showMessageDialog(this, "Please fill in all the blanks.");

        }else{
            
        Employee e= employeeDirectory.addNewEmployee();
        
        e.setName(name);
        e.setDepartment(department);
        e.setId(id);
        e.setAge(age);
        e.setGender(gender);
        e.setStartday(startDate);
        e.setLevel(level);
        e.setTitle(title);
        e.setSupervisor(supervisor);
        e.setMobile(mobile);
        e.setEmail(email);
        e.setImage(photo);
        
        JOptionPane.showMessageDialog(this, "New Employee Added");
        
        txtAge.setText("");
        txtDepartment.setText("");
        txtEmail.setText("");
        txtEmployeeID.setText("");
        txtLevel.setText("");
        txtMobile.setText("");
        txtName.setText("");
        txtStartDate.setText("");
        txtSupervisor.setText("");
        txtTitle.setText("");
        lblImage.setIcon(null);
        buttonGroup1.clearSelection();
        }
        }  

    }//GEN-LAST:event_btnCreateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extension Suppported", "jpg", "png", "jpeg", "gif");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            ImageIcon imIco = new ImageIcon(file.toString());
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            
            lblImage.setIcon(new ImageIcon(imgFit));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtEmployeeIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIDKeyPressed
        // TODO add your handling code here:
        char c  = evt.getKeyChar();
        if(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE){
            txtEmployeeID.setEditable(true);
        }else{
            txtEmployeeID.setEditable(false);            
        }
    }//GEN-LAST:event_txtEmployeeIDKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        char c  = evt.getKeyChar();
        if(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE){
            txtAge.setEditable(true);
        }else{
            txtAge.setEditable(false);            
        }
    }//GEN-LAST:event_txtAgeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtStartDate;
    private javax.swing.JTextField txtSupervisor;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    public String getButtonGroupText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    } 
}
